language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - 3.8
  - pypy
  - pypy3
  - nightly

allow_failures:
  - python: 2.7
  - python: 3.4
  - python: pypy
  - python: nightly

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - make test

after_success:
  coveralls
